### ISSUE TITLE
Sim Loop crashed

### ISSUE THREAD

**Issue by grrrisu** [grrrisu/xim2#9]
https://github.com/grrrisu/Ximula/blob/main/lib/sim/loop.ex#L193

https://github.com/grrrisu/Ximula/blob/main/lib/sim/loop.ex#L104

```
[error] GenServer Biotope.Sim.Loop terminating
** (KeyError) FATAL: Queue could not be found. Restarting Sim.Loop!
    (ximula 0.2.0) lib/sim/loop.ex:193: Ximula.Sim.Loop.find_and_update_queue!/3
    (ximula 0.2.0) lib/sim/loop.ex:104: Ximula.Sim.Loop.handle_info/2
    (stdlib 5.2) gen_server.erl:1095: :gen_server.try_handle_info/3
    (stdlib 5.2) gen_server.erl:1183: :gen_server.handle_msg/6
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {#Reference<0.0.54915.1913128979.4209573889.262024>, {139787, {%{queue: :normal, results: [%{ok: 5000, time: 120782, errors: 0, simulation: :vegetation}, %{ok: 501, time: 15691, errors: 0, simulation: :herbivore}, %{ok: 0, time: 98, errors: 0, simulation: :predator}]}, %Ximula.Sim.Queue{name: :normal, func: {Biotope.Simulation, :sim, [data: Biotope.Data]}, interval: 200, timer: #Reference<0.1913128979.4209508353.244018>, task: nil}}}}
State: %{running: true, supervisor: Biotope.Sim.Loop.Task.Supervisor, queues: [%Ximula.Sim.Queue{name: :normal, func: {Biotope.Simulation, :sim, [data: Biotope.Data]}, interval: 200, timer: nil, task: nil}], sim_args: []}
[error] GenServer #PID<0.1402857.0> terminating
** (stop) exited in: GenServer.call(Biotope.Sim.Loop, :get_queues, 5000)
    ** (EXIT) an exception was raised:
        ** (KeyError) FATAL: Queue could not be found. Restarting Sim.Loop!
            (ximula 0.2.0) lib/sim/loop.ex:193: Ximula.Sim.Loop.find_and_update_queue!/3
            (ximula 0.2.0) lib/sim/loop.ex:104: Ximula.Sim.Loop.handle_info/2
            (stdlib 5.2) gen_server.erl:1095: :gen_server.try_handle_info/3
            (stdlib 5.2) gen_server.erl:1183: :gen_server.handle_msg/6
            (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
    (elixir 1.16.0) lib/gen_server.ex:1114: GenServer.call/3
    (xim2_web 0.1.0) lib/xim2_web/live/biotope/index.ex:115: anonymous fn/2 in Xim2Web.BiotopeLive.Index.main_section/1
    (phoenix_live_view 0.20.11) lib/phoenix_live_view/diff.ex:519: Phoenix.LiveView.Diff.invoke_dynamic/2
    (phoenix_live_view 0.20.11) lib/phoenix_live_view/diff.ex:391: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.11) lib/phoenix_live_view/diff.ex:546: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.11) lib/phoenix_live_view/diff.ex:389: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.11) lib/phoenix_live_view/diff.ex:546: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.11) lib/phoenix_live_view/diff.ex:389: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.11) lib/phoenix_live_view/diff.ex:136: Phoenix.LiveView.Diff.render/3
    (phoenix_live_view 0.20.11) lib/phoenix_live_view/channel.ex:954: anonymous fn/4 in Phoenix.LiveView.Channel.render_diff/3
    (telemetry 1.2.1) /Users/taadiale/development/test/xim2/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.20.11) lib/phoenix_live_view/channel.ex:949: Phoenix.LiveView.Channel.render_diff/3
    (phoenix_live_view 0.20.11) lib/phoenix_live_view/channel.ex:576: Phoenix.LiveView.Channel.mount_handle_params_result/3
    (phoenix_live_view 0.20.11) lib/phoenix_live_view/channel.ex:1170: Phoenix.LiveView.Channel.verified_mount/8
    (phoenix_live_view 0.20.11) lib/phoenix_live_view/channel.ex:84: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 5.2) gen_server.erl:1095: :gen_server.try_handle_info/3
    (stdlib 5.2) gen_server.erl:1183: :gen_server.handle_msg/6
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {Phoenix.Channel, %{"flash" => nil, "params" => %{"_csrf_token" => "XBINGCsTVWYiOWQcZQMZHykXLiE6Kj1b5CZjHa-UtvQS7rOQEuzNyoe6", "_mounts" => 1, "_track_static" => ["http://localhost:4000/assets/app.css", "http://localhost:4000/assets/app.js"]}, "session" => "SFMyNTY.g2gDaAJhBXQAAAAIdwJpZG0AAAAUcGh4LUY3NDJWVTZGMGppblBCSEJ3B3Nlc3Npb250AAAAAHcKcGFyZW50X3BpZHcDbmlsdwZyb3V0ZXJ3FUVsaXhpci5YaW0yV2ViLlJvdXRlcncEdmlld3cgRWxpeGlyLlhpbTJXZWIuQmlvdG9wZUxpdmUuSW5kZXh3CXJvb3Rfdmlld3cgRWxpeGlyLlhpbTJXZWIuQmlvdG9wZUxpdmUuSW5kZXh3CHJvb3RfcGlkdwNuaWx3DGxpdmVfc2Vzc2lvbmgCdwdkZWZhdWx0bggAJT7pVTXNuRduBgATyXpXjgFiAAFRgA.Cc7Ijg57XM7zjQNjdoagxIr7cUphBygEP5JpRHrEVJk", "static" => "SFMyNTY.g2gDaAJhBXQAAAADdwJpZG0AAAAUcGh4LUY3NDJWVTZGMGppblBCSEJ3BWZsYXNodAAAAAB3CmFzc2lnbl9uZXdqbgYAFMl6V44BYgABUYA.qbZjcq97KOsyys1wU2a7vn2XESk3Crv_T5UDaHUvtUg", "url" => "http://localhost:4000/biotope"}, {#PID<0.1399798.0>, #Reference<0.1913128979.4209246210.231847>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.Channel, channel_pid: nil, endpoint: Xim2Web.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, joined: false, join_ref: "35", private: %{connect_info: %{session: %{"_csrf_token" => "iQWrcrx3VO5ORqVNlbToCEXm"}}}, pubsub_server: Xim2.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lv:phx-F742VU6F0jinPBHB", transport: :websocket, transport_pid: #PID<0.1399798.0>}}
State: #Reference<0.1913128979.4209246210.231850>
[error] exited in: GenServer.call(Biotope.Sim.Loop, :get_queues, 5000)
    ** (EXIT) an exception was raised:
        ** (KeyError) FATAL: Queue could not be found. Restarting Sim.Loop!
            (ximula 0.2.0) lib/sim/loop.ex:193: Ximula.Sim.Loop.find_and_update_queue!/3
            (ximula 0.2.0) lib/sim/loop.ex:104: Ximula.Sim.Loop.handle_info/2
            (stdlib 5.2) gen_server.erl:1095: :gen_server.try_handle_info/3
            (stdlib 5.2) gen_server.erl:1183: :gen_server.handle_msg/6
            (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

**Comment by grrrisu** [comment]
fixed with https://github.com/grrrisu/Ximula/pull/24
